config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :carts

  resources :cart_items, only: [:create], as: 'create_cart_items'
  resources :cart_items, only: [:update], as: 'update_cart_items'
  resources :cart_items, only: [:destroy], as: 'destroy_cart_items'

  get 'cart/empty_cart', to: 'carts#empty_cart', as: 'clear_cart_items'
  post '/add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'add_to_cart'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
    # confirmations: 'users/confirmations',
    # unlocks: 'users/unlocks',
    # omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Default root
  root 'products#index'
end

app/views/layouts/shared/_cart.html.erb
<div class="row row-cols-12 g-3 bg-light p-3">
   <% @cart_items.each do |cart_item| %> 
   <div class="col-xs-12">
      <div class="card">
         <div class="card-body">
            <div class="d-flex">
               <h5 class="card-title"><%= cart_item.product.product_code %> | <%= cart_item.product.name %></h5>
               <h3 class="card-title ms-auto"> <%= cart_item.total_price.round(2) %> € </h3>

            </div>
            <div class="d-flex">
               <div class="input-group mb-3">
                  <%= form_with url: update_cart_item_path(cart_item), class: "d-flex", method: :patch do |form| %>  
                  <%= form.number_field :quantity, value: cart_item.quantity, class: "form-control" %>
                  <%= form.submit "Update", class: "btn btn-outline-secondary" %>
                  <% end %>
               </div>
            </div>
            <% if cart_item.discount_amount > 0 %>
               <p><%= t("cart.savings_text") %> <%= cart_item.discount_amount %> €  </p>
            <% end%>
         </div>
      </div>
      <div>      
         <%= button_to t("cart.remove_product"), destroy_cart_item_path(cart_item), method: :delete, class: "ms-auto btn btn-primary-outline red" %>
      </div>
   </div>
   <% end %>
   <div class="totals px-3">
      <% if @cart_items.present?%>
         <%= button_to t("cart.clear_cart"), clear_cart_items_path, method: :get, class: "btn btn-primary-outline bg-secondary text-white" %>
      <% end %>
      <hr>
      <h5>Total: <%= current_cart.total_price.round(2) %> €  </h5>
      <hr>
      <p><%= t("cart.cart_products", items: @number_of_cart_items ) %></p>
   </div>
</div>

app/views/layouts/shared/_header.html.erb
<div class="bg-light">
   <div class="container ">
      <div class="row">
         <nav class=" navbar navbar-expand-lg navbar-light ">
            <a class="navbar-brand pt-3 ps-2" href="#">
               <h5><%= t("menu.company") %></h5>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Amenitiz Challenge</span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
               <% if user_signed_in? %>
               <ul class="navbar-nav">
                  <li class="nav-item active">
                     <a class="nav-link" href="/"><%= t("menu.home") %></a>
                  </li>
                  
               </ul>
               <ul class="navbar-nav ms-auto me-2">
                  <li class="nav-item active pe-2">
                     <a class="nav-link" href="/carts/show">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </svg>
                     </a>
                  </li>
                  <%= button_to t("user.sign_out"), destroy_user_session_path, class: "btn btn-danger",method: :delete %>
               </ul>
               <% else %>
               <ul class="navbar-nav ms-auto me-2">
                  <li class="nav-item ml-auto">
                     <a class=" btn btn-primary me-2" role="button"  href="/users/sign_in"><%= t("user.login") %></a>
                  </li>
                  <a class="btn btn-secondary" href="/users/sign_up"><%= t("user.sign_up") %></a></li>
                  </li>
               </ul>
               <% end %>
            </div>
         </nav>
      </div>
   </div>
</div>