config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :carts

  resources :cart_items, only: [:create], as: 'create_cart_items'
  resources :cart_items, only: [:update], as: 'update_cart_items'
  resources :cart_items, only: [:destroy], as: 'destroy_cart_items'

  get 'cart/empty_cart', to: 'carts#empty_cart', as: 'clear_cart_items'
  post '/add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'add_to_cart'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
    # confirmations: 'users/confirmations',
    # unlocks: 'users/unlocks',
    # omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Default root
  root 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :discount, optional: true

  validates_uniqueness_of :product_code, on: :create, message: 'must be unique'
  validates :name, :price, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = Product.all
    @cart_items = current_cart.cart_items
    @number_of_cart_items = @cart_items.sum(&:quantity) || 0
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/partials/_product.html.erb
<div class="row row-cols-2 g-3 products">
  <% @products.each do |product| %>
    <div class="col">
      <div class="card">
        <img src="<%= product.image%>" class="card-img-top productImage">
        <div class="card-body">
          <div class="position-absolute top-0 end-0 py-1 px-3 text-end bg-white"> 
              <strong><%= t("product.reference") %>: </strong> 
              <small><%=  product.product_code %></small>
          </div>
          <h5 class="card-title"><strong><%= product.name %></strong></h5>
          <h3 class="card-title ms-auto"><%= product.price %> €</h3>
          <p class="card-text"><%= product.discount.name if product.discount %></p>
          <%= button_to t("cart.add_to_cart"), add_to_cart_path(product_id: product.id), method: :post, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>